### ISSUE TITLE
Result reproduction

### ISSUE THREAD

**Issue by youthHan** [zd11024/NaviLLM#7]
Hi Thanks for open-sourcing this work. I have problems reproducing the results in the paper, looking forward to your help.

I have replicated twice the multitask w/o pertaining experiments. However, I fail to reproduce the results. My results are
<img width="814" alt="image" src="https://github.com/zd11024/NaviLLM/assets/18671115/14cb09a6-d2b9-4654-b61e-4977cc8d9e0f">

For reference, I have also tested your released checkpoint on R2R and REVERIE, the results are
<img width="814" alt="image" src="https://github.com/zd11024/NaviLLM/assets/18671115/c98f20bc-96bf-4095-b6ed-f771dee5111a">

**Comment by zd11024** [comment]
It seems the results come from the validation split, right?
Could you provide more details about your implementation? Did you change any hyper-parameters or turn off some subtasks? And how do you choose checkpoints for testing?

**Comment by youthHan** [comment]
Yes. The results are from validation. I use the scripts provided from training and on-the-fly testing. It adopts the best model to test on validation.
![image](https://github.com/zd11024/NaviLLM/assets/18671115/071bc407-3b99-4b55-8d85-98fa0c319161)

As for the code, the only modifications are to adapt the LMDB to work on my cluster
![image](https://github.com/zd11024/NaviLLM/assets/18671115/9d9b691f-d0da-4789-b947-bf9af8517071)
![image](https://github.com/zd11024/NaviLLM/assets/18671115/25bea9b1-a03b-4550-84b6-34b5ac542c58)
![image](https://github.com/zd11024/NaviLLM/assets/18671115/2f8318dd-801d-4689-903b-91223adf1af7)
I move the creation of self.sim to each rank during their data fetching.

**Comment by zd11024** [comment]
It looks a bit weird. I have tried this script twice and the results are relatively stable in my trials (As shown in the following figures). 
Would you please share your training log file with me?

![image](https://github.com/zd11024/NaviLLM/assets/34681526/7f467417-a5e6-495d-8b3d-e0ca89ae21e6)
![image](https://github.com/zd11024/NaviLLM/assets/34681526/495b9f53-48f9-447d-87db-8940f40753e8)

**Comment by youthHan** [comment]
The losses of first few epochs are similar to your log. But the val numerical results are much better. It is quite wired. Do you think the simulator environment may be a cause?

**Comment by zd11024** [comment]
I suspect it may be because we actually used [vicuna-7b-delta-v1.1](https://huggingface.co/lmsys/vicuna-7b-delta-v1.1) but mistakenly thought we were using [vicuna7b-delta-v0](https://huggingface.co/lmsys/vicuna-7b-delta-v0). 
I will confirm it soon.

**Comment by zd11024** [comment]
For Vicuna-7b-delta-v0,  the `delta model' cannot be used directly. Users have to apply it on top of the original LLaMA weights to get actual Vicuna weights. See [instructions](https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md#how-to-apply-delta-weights-for-weights-v11-and-v0).
Have you performed this transformation before using the model? Otherwise, the obtained vicuna parameters may be abnormal.

**Comment by youthHan** [comment]
So the model is Vicuna-v0?

The Vicuna model on my side should be ok, as I have already used it for many other models and tasks.

**Comment by zd11024** [comment]
It takes me some time to verify. Apologize for the inconvenience.

**Comment by youthHan** [comment]
That's fine. Thank you for getting back to me.

Do you have other ideas about the performance?

**Comment by zd11024** [comment]
It seems that we actually use vicuna-7b-v1.1.
You can replace the model with vicuna-7b-v1.1, please let me know if you still have problems. 
Sorry for the inconvenience.

**Comment by youthHan** [comment]
It's actually good news. Let me have a try.

**Comment by zd11024** [comment]
Hi, have you successfully reproduced the results?

**Comment by youthHan** [comment]
The model is in training. 

Also, I have encountered another issue: if I use vicuna-v0 tokenizer testing model on ScanQA, everything is fine except the numbers don't match; whlist I use vicuna-v1.1 tokenizer, the code reports error. I can make sure that because I have tried several times with different machines and environments (including the one you provided in requirement.txt). Testing on R2R and REVERIE is fine with both tokenizers.

The error is reported on
https://github.com/zd11024/NaviLLM/blob/09f5cbeac9bf96d1a1053785d6a32df888ffeaeb/models/nav_model.py#L395

Error trace:
Traceback (most recent call last):
  File "/xxx/NaviLLM/train.py", line 297, in <module>
    main()
  File "/xxx/NaviLLM/train.py", line 234, in main
    results = val_one_epoch(
  File "/home/xx/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/xxx/NaviLLM/train.py", line 140, in val_one_epoch
    preds = agent.validate(
  File "/xxx/NaviLLM/tasks/agents/llava.py", line 64, in validate
    outputs = model("3dqa", batch, training=False, **generation_kwargs)
  File "/home/xx/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxx/NaviLLM/models/nav_model.py", line 145, in forward
    return self.forward_3dqa(mode, batch, **kwargs)
  File "/xxx/NaviLLM/models/nav_model.py", line 421, in forward_3dqa
    generated_sentences = self.lang_model.tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3446, in batch_decode
    return [
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3447, in <listcomp>
    self.decode(
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3486, in decode
    return self._decode(
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/home/xx/.local/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 129, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/home/xx/.local/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1179, in _batched_func
    return _func(self, arg)
  File "/home/xx/.local/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1172, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

The generated_ids when reporting bug are:
[[1, 29871, 29906, 2], [1, 2175, 2, -1]]

**Comment by youthHan** [comment]
Debugging..

**Comment by youthHan** [comment]
The vicuna v1.1 I use is https://huggingface.co/lmsys/vicuna-7b-v1.1 
Though I think it should not be problem, I need to confirm this.

**Comment by youthHan** [comment]
The point is the loaded tokenizer fails to decode -1, which is not in the vocabulary. Can you check whether this also an issue on your side? By the way, please to help to check the config.json in the vicuna model you use.

Now I replace the token id -1 with your pad token id
Traceback (most recent call last):
  File "train.py", line 297, in <module>
    main()
  File "train.py", line 234, in main
    results = val_one_epoch(
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 140, in val_one_epoch
    preds = agent.validate(
  File "/mnt/bn/kinetics-lp-maliva-v6/playground_projects/NaviLLM/tasks/agents/llava.py", line 64, in validate
    outputs = model("3dqa", batch, training=False, **generation_kwargs)
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/bn/kinetics-lp-maliva-v6/playground_projects/NaviLLM/models/nav_model.py", line 148, in forward
    return self.forward_3dqa(mode, batch, **kwargs)
  File "/mnt/bn/kinetics-lp-maliva-v6/playground_projects/NaviLLM/models/nav_model.py", line 414, in forward_3dqa
    generate_ids = self.lang_model.generate(
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/mnt/bn/kinetics-lp-maliva/envs/conda/envs/navillm3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/bn/kinetics-lp-maliva-v6/playground_projects/NaviLLM/models/modified_lm.py", line 109, in forward
    if cand_locations.sum() != 0:
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by zd11024** [comment]
The model is vicuna-7b-v1.1. However, I found that the tokenizer is slightly different from the current version. The pas token in my config is set to 0. 
![image](https://github.com/zd11024/NaviLLM/assets/34681526/b623ff51-3f5d-4c23-8d4e-1944414c032b)

**Comment by zd11024** [comment]
The pad_token_id of vicuna-7b-v1.1 is -1, and the pad_token_id of vicuna-7b-delta-v1.1 is 0 (their parameters are exactly the same). Thus, -1 is automatically produced in the generation process, causing this error. To solve this problem, you can either modify the pad_token_id in the config, or manually pass it in when calling the generate function.

**Comment by zd11024** [comment]
Hello, have you addressed the problem and reproduced the results?

**Comment by youthHan** [comment]
I prepared vicuna-v1.1 using the delta model by FastChat. The overall val-unseen score is 2.93, lower than the released training log. Specifically on REVERIE by 2 points, on ScanQA by ~1 point. But things are much better.

**Comment by zd11024** [comment]
It's good to hear that. Thanks for your feedback and discussion!
